name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build
        run: xcodebuild -scheme PerceptronViz -destination 'platform=macOS' build

      - name: Test
        run: xcodebuild test -scheme PerceptronViz -destination 'platform=macOS'
